### ISSUE TITLE
gcdump crash on macOS

### ISSUE THREAD

**Issue by gengjiawen** [hsiaosiyuan0/slowjs#12] opened 2023-12-07 08:57 UTC
```console
qjs(26627,0x7ff84a9ece80) malloc: *** error for object 0x7fb: pointer being freed was not allocated
qjs(26627,0x7ff84a9ece80) malloc: *** set a breakpoint in malloc_error_break to debug
```

![CleanShot 2023-12-07 at 16 56 28@2x](https://github.com/hsiaosiyuan0/slowjs/assets/3759816/f77ae55f-906b-43a2-b586-b43c2e821d99)

**Comment by hsiaosiyuan0** [comment] 2023-12-07 15:23
attach the js source please, if it's possible

**Comment by gengjiawen** [comment] 2023-12-08 01:37
```js
var o = function AAAA(){}

o.data = {
  a: { a1: { a2: 1 } },
  b: { b1: { b2: 1 } },
  c: function () {
    return 1;
  },
  d: new ArrayBuffer((1 << 20) * 50, 0),
  e: new Uint16Array((1 << 20) * 50, 0),
};

__js_gcdump_objects();
print(o); // retain the obj to prevent it from being freed
```

I am on clang-15 on macOS 14

**Comment by hsiaosiyuan0** [comment] 2023-12-09 02:18
fixed in branch [fix/macos-crash](https://github.com/hsiaosiyuan0/slowjs/commit/f6e6be29bfa865256c39b79072e923ac4f3be8c3):

[![asciicast](https://asciinema.org/a/kgNZtly3S1sFj733n2KlnIgrF.svg)](https://asciinema.org/a/kgNZtly3S1sFj733n2KlnIgrF)

the crash caused by the unsafe foreach in `kid_hashmap_free` and libc shipped in some apple clang do the mem address check

**Comment by gengjiawen** [comment] 2023-12-09 14:52
> fixed in branch [fix/macos-crash](https://github.com/hsiaosiyuan0/slowjs/commit/f6e6be29bfa865256c39b79072e923ac4f3be8c3):
> 
> [![asciicast](https://camo.githubusercontent.com/535c16460f04294a28419868c30dd3622fbd936898b545d388637ca0c87ede1e/68747470733a2f2f61736369696e656d612e6f72672f612f6b674e5a746c7933533173466a3733336e324b6c6e496772462e737667)](https://asciinema.org/a/kgNZtly3S1sFj733n2KlnIgrF)
> 
> the crash caused by the unsafe foreach in `kid_hashmap_free` and libc shipped in some apple clang do the mem address check

Any plan merge to main ?

**Comment by hsiaosiyuan0** [comment] 2023-12-09 14:58
does it resolve the crash on your device, I'll merge it asap if it works

**Comment by gengjiawen** [comment] 2023-12-10 13:13
> does it resolve the crash on your device, I'll merge it asap if it works

Yeap. works like a charm.

**Closed** 2023-12-11 04:35 UTC
